version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: haedok-redis
    ports:
      - "6379:6379"               # 호스트 6379포트를 컨테이너 6379포트에 매핑
    volumes:
      - redis_data:/data          # 데이터 지속성을 위한 볼륨 마운트
    restart: unless-stopped       # 수동으로 중지하기 전까지 자동 재시작
    command: redis-server --appendonly yes    # AOF(Append Only File) 활성화로 데이터 지속성 보장

volumes:
  redis_data:
    driver: local                # 로컬 볼륨 드라이버 사용