spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # 실행전 db_dev 파일 삭제 필요
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:dummy}  # 로컬용 더미값
        secret-key: ${AWS_SECRET_ACCESS_KEY:dummy}

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# 개발용 상세 로깅
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG

# 쿠키 보안 설정 (HTTP 환경용)
custom:
  cookie:
    secure: true
    same: "Lax"

#  # AI 설정
#  ai:
#    openai:
#      chat:
#        options:
#          model: "gemini-2.0-flash"
