spring:
  profiles:
    active: dev

  config:
    import: optional:file:.env[.properties]

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  application:
    name: back

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_OAUTH2_CLIENT_ID}
            scope: profile_nickname # 카카오 닉네임만 가져옴
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.backUrl}/{action}/oauth2/code/{registrationId}'
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            redirect-uri: '${custom.site.backUrl}/{action}/oauth2/code/{registrationId}'
            client-name: Google
            scope: profile
          naver:
            client-id: ${NAVER_OAUTH2_CLIENT_ID}
            client-secret: ${NAVER_OAUTH2_CLIENT_SECRET}
            scope: profile_nickname # 네이버 닉네임만 가져옴
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.backUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}  # 로컬용 더미값
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: team2-app-s3-bucket

  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        base-url: "https://generativelanguage.googleapis.com/v1beta/openai/"
        options:
          model: "gemini-2.0-flash-exp"
          temperature: 0.8
          max-tokens: 800
        completions-path: "/chat/completions"

springdoc:
  default-produces-media-type: application/json;charset=UTF-8

server:
  port: 8080
  forward-headers-strategy: native
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: ${BASE_URL}
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    cookieDomain: ${custom.dev.cookieDomain}
    frontUrl: ${custom.dev.frontUrl}
    backUrl: ${custom.dev.backUrl}
    name: ssoul
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  accessToken:
    expirationSeconds: "#{60*15}"
  refreshToken:
    expirationSeconds: "#{60*60*24*30}"


management:
  endpoints:
    web:
      base-path: /actuator            # 기본값이지만 명시
      exposure:
        include: health,info          # 필요시 metrics 등 추가
  endpoint:
    health:
      probes:
        enabled: true                 # /actuator/health/{liveness,readiness} 활성화
      show-details: never             # 프로브 용도면 never 권장(민감정보 차단)


chatbot:
  history:
    max-conversation-count: 5
  system:
    prompt-file: classpath:prompts/chatbot-system-prompt.txt
    rules-file: classpath:prompts/chatbot-response-rules.txt