# 프로덕션 환경 설정
#spring:
#  datasource:
#    url: ${DATABASE_URL}
#
#

spring:
  autoconfigure:
    exclude:
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 삭제 재성성 과정에서 외래키 제약발생. create 변경 후 배포 테스트
    properties:
      hibernate:
        show_sql: false
  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    com.back: INFO
    root: WARN

# 쿠키 보안 설정
custom:
  cookie:
    secure: true
    same: "None"
    domain: ${custom.prod.cookieDomain}
  site:
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
    name: ssoul
